
modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="rubycraft" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Rubycraft Mod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://github.com/RichardPalotai/Minecraftmodding" #optional

logoFile="examplemod.png" #optional

credits="Thanks for downloading Rubycraft." #optional

authors="Richard Palotai" #optional

description='''
A mod that contains many Ruby items and blocks.
Various of ideas about Ruby and how It get in the game.
'''

[[dependencies.rubycraft]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[32,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.rubycraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
